### ISSUE TITLE
Modification in API

### ISSUE THREAD

**Issue by sksingh55** [RahulYadav119/PYTHON-REST-API-Without-Framework-#1]
How to create URL like localhost:8080/getList?num=1 which will return 1 value from list in your current code?

**Comment by RahulYadav119** [comment]
@sksingh55 you can do that using self.path in your do_Get() function.
self.path will give you the entered URL from which you can easily read the value of num using some split()'s and if-else.
It will be a little bit of excess code but it'll do the magic.

For more clarity, check this

```
def do_GET(self):
        #defining all the headers
        self.send_response(200)
        self.send_header('Content-type','text/json')
        self.end_headers()
        pth = self.path          # pth  =  "/getList?num=1"
        field = pth.split('?')   # field = [ "/getList", "num=1"]
        if len(field) > 1:
            value = field[1].split('=')[1]    # value = "1"
            self.wfile.write(json.dumps(data[value]).encode())
```
The above code will give Display `"First"` on the browser screen (which is as per the db.json).
I hope this is what you were looking for. By the way, the same functionality is offered by the do_VIEW() funtion.

**Comment by RahulYadav119** [comment]
Please tell if that solves the issue for you

**Comment by RahulYadav119** [comment]
> How to create URL like localhost:8080/getList?num=1 which will return 1 value from the list in your current code?

@sksingh55 you can do that using self.path in your do_Get() function.
self.path will give you the entered URL from which you can easily read the value of num using some split()'s and if-else.
It will be a little bit of excess code but it'll do the magic.

For more clarity, check this

def do_GET(self):
        #defining all the headers
        self.send_response(200)
        self.send_header('Content-type','text/json')
        self.end_headers()
        pth = self.path          # pth  =  "/getList?num=1"
        field = pth.split('?')   # field = [ "/getList", "num=1"]
        if len(field) > 1:
            value = field[1].split('=')[1]    # value = "1"
            self.wfile.write(json.dumps(data[value]).encode())

The above code will give Display "First" on the browser screen (which is as per the db.json).
I hope this is what you were looking for. By the way, the same functionality is offered by the do_VIEW() function.
Please tell if that solves your issue, If so then I can close the issue. :)

**Comment by RahulYadav119** [comment]
> How to create URL like localhost:8080/getList?num=1 which will return 1 value from list in your current code?

@sksingh55 you can do that using self.path in your do_Get() function.
self.path will give you the entered URL from which you can easily read the value of num using some split()'s and if-else.
It will be a little bit of excess code but it'll do the magic.

For more clarity, check this

```
def do_GET(self):
      #defining all the headers
      self.send_response(200)
       self.send_header('Content-type','text/json')
       self.end_headers()
       pth = self.path # pth = "/getList?num=1"
       field = pth.split('?') # field = [ "/getList", "num=1"]
       if len(field) > 1:
       value = field[1].split('=')[1] # value = "1"
       self.wfile.write(json.dumps(data[value]).encode())

```
The above code will give Display `"First"` on the browser screen (which is as per the db.json).
I hope this is what you were looking for. By the way, the same functionality is offered by the do_VIEW() function.
Please tell if that solves your issue, If so then I can close the issue. :)
